In [1]:
import numpy as np

## creation of empty numpy 

In [3]:
emp=np.empty([2,2]) #first parameter as shape
print(emp)

[[0.0000000e+000 1.1610603e-311]
 [1.1610603e-311 1.1610603e-311]]


In [4]:
emp1=np.empty(shape=[3,3])
emp1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# creating of zeros 

In [11]:
z=np.zeros(shape=[3,3],dtype='int32')
print(z)
#print(z.dtype())

[[0 0 0]
 [0 0 0]
 [0 0 0]]


### creating of the array with one value

In [16]:
o=np.ones(shape=[3,3],dtype='float64')
print(o)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## using of full

In [20]:
f=np.full(shape=[5,5],fill_value=5)
print(f)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [22]:
f=np.full(shape=[5,5],fill_value=5,dtype='float64')
f

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

## identity matrix

In [23]:
i=np.eye(4)
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# np.arange()

In [26]:
a=np.arange(1,11,dtype='float64')
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [29]:
a=np.arange(1,21,2)
print(a)
a=a.reshape([2,5])
a

[ 1  3  5  7  9 11 13 15 17 19]


array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [33]:
b=np.arange(2,21,2)
print(b)
b=b.reshape([5,2])
b

[ 2  4  6  8 10 12 14 16 18 20]


array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

## np.linspace

In [37]:
l=np.linspace(5,20,10)
print(l)
print(len(l))

[ 5.          6.66666667  8.33333333 10.         11.66666667 13.33333333
 15.         16.66666667 18.33333333 20.        ]
10
